// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDy7CLLKGOaWwH5-Sz1-E3fgonFJntFTo4',
    appId: '1:597509631660:web:095ef79399a7c459143909',
    messagingSenderId: '597509631660',
    projectId: 'quran-backup-916e3',
    authDomain: 'quran-backup-916e3.firebaseapp.com',
    storageBucket: 'quran-backup-916e3.appspot.com',
    measurementId: 'G-F656VKRKRV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpPyVEdJzQlQrovJTveu36I5VBwwSmSxw',
    appId: '1:597509631660:android:e1fde4b3afae37b1143909',
    messagingSenderId: '597509631660',
    projectId: 'quran-backup-916e3',
    storageBucket: 'quran-backup-916e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAz8ralIsWIl5rqsq4AovmRzCehvd_e8DA',
    appId: '1:597509631660:ios:8ba18d9d5e87aa0c143909',
    messagingSenderId: '597509631660',
    projectId: 'quran-backup-916e3',
    storageBucket: 'quran-backup-916e3.appspot.com',
    iosBundleId: 'com.example.quran',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAz8ralIsWIl5rqsq4AovmRzCehvd_e8DA',
    appId: '1:597509631660:ios:14db7fdf1863aa3f143909',
    messagingSenderId: '597509631660',
    projectId: 'quran-backup-916e3',
    storageBucket: 'quran-backup-916e3.appspot.com',
    iosBundleId: 'com.example.quran.RunnerTests',
  );
}
